### ISSUE TITLE
Error in scf.tl.branch_specific

### ISSUE THREAD

**Issue by min0609** [LouisFaure/scFates#13]
Hi,
First of all, thank you for this wonderful tool.

I was following the tutorial 'Tree analysis', but when I ran the following command line, I got the error message below:
`scf.tl.branch_specific(adata,root_milestone="follicular1",milestones=["PTC2","ATC1","ATC3", "PTCEO", "BifATC"],effect=2)`

<img width="998" alt="image" src="https://user-images.githubusercontent.com/105622235/221132202-02e8685b-01de-450e-8a14-3cf3eb8af9c2.png">

Could you please suggest me how to solve the problem?

I also would like to know the difference between seg and milestone.

Thank you!

**Comment by LouisFaure** [comment]
Apologies for the lack of answer, I am currently doing a sabbatical.

A segment is considered as a section of the tree from one tip or fork to another, while milestones designate the actual tips and forks. The latter is easier to use when one want to specify a subset of trajectory to focus on for analysis such as branch DE.

This error tells that it cannot find any data in `.uns` part of your anndata with the keys of your trifurcation. Have you run `test_fork` with the same milestones before?

In more details, a cell is given a milestone that is the closest fork or tip in term of pseudotime distance
