### ISSUE TITLE
dendrogram Tree line and cells are not alligned in the plot

### ISSUE THREAD

**Issue by willey2020** [LouisFaure/scFates#16]
Hello! Thank you for this great package!

I have an issue while running the dendrogram, not sure why the cells are not aligned with the tree line, could I ask how to troubleshoot this?...
Thank you so much!

<img width="313" alt="tree" src="https://github.com/LouisFaure/scFates/assets/72377061/bfeda8e7-7f33-4a91-ba97-edeabfbf3a54">

Sorry for bugging, after I restart the kernel, everything works. Close the issue.

**Comment by willey2020** [comment]
It happens again, and seems happening in #7 issue as well. 
https://github.com/LouisFaure/scFates/issues/7#issuecomment-1213420148

Thank you!

**Comment by LouisFaure** [comment]
Could you send an anonymized anndata file so I can have a look myself?

**Comment by willey2020** [comment]
Sorry! Today a couple of hours ago I tried to debug and just find out what happened. I used Arch Linux and it keeps showing this issue. Not sure exactly why, today after I tried to run all the analysis on Ubuntu 22 with new installed conda/scfates, everything works perfectly. 
Thank you so much! I think installing on a fresh system will make it work! Thank you again for this great package!
