### ISSUE TITLE
When running scf.tl.curve, module 'networkx' has no attribute 'to_scipy_sparse_matrix'

### ISSUE THREAD

**Issue by yedeer12** [LouisFaure/scFates#17]
I think the different version of networkx and elpigraph causes this problem. scFates 1.0.2 requires elpigraph-python==0.2.7, but elpigraph-python==0.2.7 uses 'to_scipy_sparse_matrix' of networkx package in 'getProjection' function. There is no 'to_scipy_sparse_matrix' function in the new networkx package, instead there is 'to_scipy_sparse_array'  in the new networkx package. elpigraph-python 0.3.1 uses 'to_scipy_sparse_array'  in the new networkx package.
![image](https://github.com/LouisFaure/scFates/assets/104268340/91811d78-7292-482c-adf8-d9d0a42a55e1)
![image](https://github.com/LouisFaure/scFates/assets/104268340/b511c2ec-63f5-44ad-b3a1-add3171605b5)

**Comment by yedeer12** [comment]
![image](https://github.com/LouisFaure/scFates/assets/104268340/527db02b-b95e-4311-bd2d-5015692e210f)

**Comment by LouisFaure** [comment]
Hi, thank you for notifying that issue! I have bow updated the package to v1.0.3 setting epigraph to 0.3.1
