### ISSUE TITLE
crashes due to rpy2 not finding the R install on conda

### ISSUE THREAD

**Issue by yedeer12** [LouisFaure/scFates#18]
After I update scFates to 1.0.3, there is a problem about rpy2. It is normal when using 1.0.2
![image](https://github.com/LouisFaure/scFates/assets/104268340/0255c524-8418-4280-b2bd-131c96b830d9)

**Comment by LouisFaure** [comment]
Hi, this seems to be an issue with rpy2 not finding your R installation. In my documentation, I show that the best course of action is to install both scFates, R and rpy2 in the same conda environment, hence the command:
```python
os.environ['R_HOME'] = sys.exec_prefix+"/lib/R/'
```
Where `sys.exec_prefix`  will automatically append the path of the python kernel you are using.

But if R is not installed in the same environment than scFates, then I would replace `sys.exec_prefix` by the path leading to your actual R installation which has `mgcv` and other dependencies installed.
