### ISSUE TITLE
issue with scf.tl.cluster and scf.pl.trends functions in notebook

### ISSUE THREAD

**Issue by 16nikita** [LouisFaure/scFates#19]
Hi, I am following the tutorial for 'basic curved trajectory analysis' and running into problems with the steps for clustering significant features. 
This line: `scf.tl.cluster(adata,knn=100,metric="correlation")` outputs the error "TypeError: cluster() got an unexpected keyword argument 'knn'", and the parameter knn is not present in the documentation, so I changed knn to n_neighbors, which worked. However, down the line, when I run scf.pl.trends, it outputs the error "IndexError: arrays used as indices must be of integer (or boolean) type". 

Do you have any suggestions for why this might be happening or how to fix it?

**Comment by LouisFaure** [comment]
Hi, some changes in the main packages were unfortunately not tested on that notebook. I have updated it (removed some irrelevant parts as well) and I have now tested with the latest version of scFates (v1.0.4): it works on my side. Let me know if that is the case for you as well.

**Comment by LouisFaure** [comment]
Now version v1.0.5 fixes the IndexError issue with `scf.pl.trends`
