### ISSUE TITLE
citing CellRank

### ISSUE THREAD

**Issue by Marius1311** [LouisFaure/scFates#2]
Hi scFates Team, thanks for this great tool! Looks fantastic, eager to check it out. Also, I'm excited that you use CellRank, seems like there are some synergies there. Just one thing, could you please add CellRank to your [references](https://scfates.readthedocs.io/en/latest/references.html) and add a link/citation to your [tutorial](https://scfates.readthedocs.io/en/latest/Conversion_from_CellRank_pipeline.html)? Thanks!

**Comment by LouisFaure** [comment]
Dear @Marius1311,

Thank you for your interest scFates! Your tool CellRank is indeed quite powerful to obtain lineages, so I thought it could be combined with scFates for more robust bifurcation analysis!

I just updated the documentation and the notebook with the reference to your preprint, the notebook was in need anyway of an introduction of CellRank, with an explanation of the rationale behind the conversion.

I also re-used your implementation of the Fisher test for the correlations from your function `lineages_drivers` on the newly introduced `tl.criticality_drivers` (as you can see I also borrowed part of the name ;) ). 

I now clearly mention the part re-used in the code as well as in the API documentation!

Please let me know if this suits you!

**Comment by Marius1311** [comment]
Amazing, @LouisFaure, thank you very much! That's perfect.
