### ISSUE TITLE
GPU mode dependencies troubleshooting

### ISSUE THREAD

**Issue by willey2020** [LouisFaure/scFates#20]
Hello! Thank you again for this great package. 

When I try to install the GPU mode package of scFates, while I am running scf.tl.tree with GPU mode, it said:

File ~/anaconda3/envs/scFates-gpu2/lib/python3.8/site-packages/scFates/tools/graph_fitting.py:270, in tree(adata, Nodes, use_rep, ndims_rep, weight_rep, method, init, ppt_sigma, ppt_lambda, ppt_metric, ppt_nsteps, ppt_err_cut, ppt_gpu_tpb, epg_lambda, epg_mu, epg_trimmingradius, epg_initnodes, epg_extend_leaves, epg_verbose, device, plot, basis, seed, copy, **kwargs)
    268 if method == "ppt":
    269     simpleppt.settings.verbosity = settings.verbosity
--> 270     ppt = simpleppt.ppt(
    271         X,
    272         W,
    273         Nodes=Nodes,
    274         init=init,
    275         sigma=ppt_sigma,
    276         lam=ppt_lambda,
    277         metric=ppt_metric,
    278         nsteps=ppt_nsteps,
    279         err_cut=ppt_err_cut,
    280         device=device,
    281         gpu_tbp=ppt_gpu_tpb,
    282         seed=seed,
    283         progress=settings.verbosity > 1,
...
--> 394 from numpy import MachAr  # NOQA
    396 from numpy import find_common_type  # NOQA
    397 from numpy import issctype  # NOQA

ImportError: cannot import name 'MachAr' from 'numpy' (/home/$$$$$/anaconda3/envs/scFates-gpu2/lib/python3.8/site-packages/numpy/__init__.py)

It looks like the program cannot import MachAr from the current version of numpy. 
I tried to downgrade the numpy, but it sounds working for finding MachAr, but then other programs come. 

Could you help to suggest how to make the scFates-GPU repo updated for matching current packages? Thank you!

**Comment by willey2020** [comment]
Thank you so much @LouisFaure !!! I will try it!!

Best, willey

**Comment by willey2020** [comment]
Sorry, I forget to close the issue. Yes, it works perfectly following your guidance and get tested. Thank you again!

**Comment by christophechu** [comment]
@LouisFaure  Can We use the new cuml. such as 24.06 or 24.04 supported by CUDA 12.*
