### ISSUE TITLE
Questions about scf.pl.single_trend'

### ISSUE THREAD

**Issue by SummerColdWind** [LouisFaure/scFates#25]
Hello, author, when I run' scf.tl.test_association' and' scf.tl.fit',' found 1661 significant features (0: 18: 28)-> added' is displayed, and then the shape of my adata also becomes (2650, 1661). Therefore, when I want to use scf.pl.single_trend to draw these 1661 genes, I can't get the expected results. Please reply if you have time. Thank you.

**Comment by LouisFaure** [comment]
Are you trying to plot all genes at the same time with `scf.pl.single_trend`? This function accept one single gene at a time. If you wish to display all genes you can use `scf.pl.trends` instead. Also showing all 1661 in one trends plot might not be as informative, I would use `scf.tl.cluster` to group gene trends before that.

**Comment by SummerColdWind** [comment]
> Are you trying to plot all genes at the same time with `scf.pl.single_trend`? This function accepts one single gene at a time.
> 
> If you wish to display all genes you can use `scf.pl.trends` instead. However, showing all 1661 in one trends plot might not be as informative, I would use `scf.tl.cluster` to group gene trends before that.

For example, there are 10,000 genes in my AnnData. After screening the hypervariable genes, there are 1,661 genes left. My idea is to draw any of the remaining 8,339 genes besides these 1,661 genes.

**Comment by LouisFaure** [comment]
If you wish to display non significant genes, I would then suggest to call fit function with all genes as following:
```python
scf.tl.fit(adata,features=adata.var_names)
```

**Comment by SummerColdWind** [comment]
> If you wish to display non significant genes, I would then suggest to call fit function with all genes as following:
> 
> ```python
> scf.tl.fit(adata,features=adata.var_names)
> ```

Tks :)
