### ISSUE TITLE
Cannot install with python 3.8, need python >=3.9

### ISSUE THREAD

**Issue by quantumdot** [LouisFaure/scFates#28]
Following the [install instructions](https://scfates.readthedocs.io/en/latest/installation.html) in the documentation, I was unable to install everything with a python3.8 environment due to the `jax` dependency (failure to solve environment). However, creating the virtual environment with python 3.9 allowed me to install all packages and dependencies.
```
conda create -n scFates -c conda-forge -c r python=3.9 r-mgcv rpy2 -y
```

It would be good to update the documentation to reflect this.

**Comment by LouisFaure** [comment]
Now fixed with v1.0.7, tested and working on more recent python version 3.11
