### ISSUE TITLE
Fitting & clustering significant features color_exp 

### ISSUE THREAD

**Issue by pmarzano97** [LouisFaure/scFates#34]
Hello world!
I've starting applying the scFates algorithm to my analysis.

I would like to know if it is possibile to change the color of cells in the function of Fitting & clustering significant features (_scf.pl.single_trend_) according to the Leiden cluster or based on the pseudotime color (so not just a single color).
In the function there is the _colo_rexp_ option but it does not allow me to assigne to the cells a color code of an observation in adata.obs.
Is it possible to do so?

Thanks so much!!

**Comment by LouisFaure** [comment]
Sorry for the quite late answer.

There are no easy way to modify the code to allow that. However, here is one trick that can be used to display any color from `obs`:


```python
ax1,ax2=scf.pl.single_trend(adata,'gene',alpha_expr=0,show=False)
sc.pl.scatter(adata,x='t',y='gene',color='clusters',ax=ax2,show=False,size=10,
              alpha=0.3,legend_loc='none')
```

Here we set the alpha of the initial scatter plot to 0, and plot on top of it using `sc.pl.scatter`
