### ISSUE TITLE
tl.branch_specific issues

### ISSUE THREAD

**Issue by AJTDaedalus** [LouisFaure/scFates#36]
I'm running tl.branch_specific and running into issues.  

When I run it with effect, no matter how loose I set effect, stf_cut, up_A, and up_p I get no results like follows:

`scf.tl.branch_specific(adata, root_milestone="373", milestones=["501", "256", "328", "377", "386", "692", "214", "652", "516", "293"], effect=0,
                       stf_cut = 0.005,
                       up_A=0,
                       up_p=0.9)`

>      branch specific features: 
>     finished --> updated 
>     .uns['373->501<>256<>328<>377<>386<>692<>214<>652<>516<>293']['fork'], DataFrame updated with additionnal 'branch' column. 

When I run it without effect, I get the following error:

`scf.tl.branch_specific(adata, root_milestone="373", milestones=["501", "256", "328", "377", "386", "692", "214", "652", "516", "293"])`

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-241-e27ba81681cb> in <module>
> ----> 1 scf.tl.branch_specific(adata, root_milestone="373", milestones=["501", "256", "328", "377", "386", "692", "214", "652", "516", "293"])
> 
> /opt/conda/lib/python3.8/site-packages/scFates/tools/bifurcation_tools.py in branch_specific(adata, root_milestone, milestones, effect, stf_cut, up_A, up_p, copy)
>     392 
>     393     df = df[(df.up_A > up_A) & (df.up_p < up_p) & (df.signi_fdr > stf_cut)]
> --> 394     df = df[((df.iloc[:, : len(milestones)] + effect) > 0).sum(axis=1) == 1]
>     395     df["branch"] = df.iloc[:, : len(milestones)].idxmax(axis=1)
>     396 
> 
> /opt/conda/lib/python3.8/site-packages/pandas/core/ops/common.py in new_method(self, other)
>      70         other = item_from_zerodim(other)
>      71 
> ---> 72         return method(self, other)
>      73 
>      74     return new_method
> 
> /opt/conda/lib/python3.8/site-packages/pandas/core/arraylike.py in __add__(self, other)
>     100     @unpack_zerodim_and_defer("__add__")
>     101     def __add__(self, other):
> --> 102         return self._arith_method(other, operator.add)
>     103 
>     104     @unpack_zerodim_and_defer("__radd__")
> 
> /opt/conda/lib/python3.8/site-packages/pandas/core/frame.py in _arith_method(self, other, op)
>    7592         self, other = ops.align_method_FRAME(self, other, axis, flex=True, level=None)
>    7593 
> -> 7594         new_data = self._dispatch_frame_op(other, op, axis=axis)
>    7595         return self._construct_result(new_data)
>    7596 
> 
> /opt/conda/lib/python3.8/site-packages/pandas/core/frame.py in _dispatch_frame_op(self, right, func, axis)
>    7619             # i.e. scalar, faster than checking np.ndim(right) == 0
>    7620             with np.errstate(all="ignore"):
> -> 7621                 bm = self._mgr.apply(array_op, right=right)
>    7622             return self._constructor(bm)
>    7623 
> 
> /opt/conda/lib/python3.8/site-packages/pandas/core/internals/managers.py in apply(self, f, align_keys, ignore_failures, **kwargs)
>     348             try:
>     349                 if callable(f):
> --> 350                     applied = b.apply(f, **kwargs)
>     351                 else:
>     352                     applied = getattr(b, f)(**kwargs)
> 
> /opt/conda/lib/python3.8/site-packages/pandas/core/internals/blocks.py in apply(self, func, **kwargs)
>     349         one
>     350         """
> --> 351         result = func(self.values, **kwargs)
>     352 
>     353         return self._split_op_result(result)
> 
> /opt/conda/lib/python3.8/site-packages/pandas/core/ops/array_ops.py in arithmetic_op(left, right, op)
>     224         # error: Argument 1 to "_na_arithmetic_op" has incompatible type
>     225         # "Union[ExtensionArray, ndarray[Any, Any]]"; expected "ndarray[Any, Any]"
> --> 226         res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
>     227 
>     228     return res_values
> 
> /opt/conda/lib/python3.8/site-packages/pandas/core/ops/array_ops.py in _na_arithmetic_op(left, right, op, is_cmp)
>     163 
>     164     try:
> --> 165         result = func(left, right)
>     166     except TypeError:
>     167         if not is_cmp and (is_object_dtype(left.dtype) or is_object_dtype(right)):
> 
> /opt/conda/lib/python3.8/site-packages/pandas/core/computation/expressions.py in evaluate(op, a, b, use_numexpr)
>     239         if use_numexpr:
>     240             # error: "None" not callable
> --> 241             return _evaluate(op, op_str, a, b)  # type: ignore[misc]
>     242     return _evaluate_standard(op, op_str, a, b)
>     243 
> 
> /opt/conda/lib/python3.8/site-packages/pandas/core/computation/expressions.py in _evaluate_standard(op, op_str, a, b)
>      68     if _TEST_MODE:
>      69         _store_test_result(False)
> ---> 70     return op(a, b)
>      71 
>      72 
> 
> TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

I've attached my fork dataframe to see if it's somehow related to my data.  I didn't get this error when doing the tutorial.
[test_fork.csv](https://github.com/user-attachments/files/17588478/test_fork.csv)

**Comment by LouisFaure** [comment]
Hi @AJTDaedalus, There is indeed a small issue in the code, where `effect=0` is wrongly filtering out all genes (due to a strictly positive check instead of `>=`).

To solve this for now I would use any non-zero value for that parameter. This will be fixed in the next version

**Comment by LouisFaure** [comment]
Now fixed in `v1.0.9`
