### ISSUE TITLE
scf.tl.pseudotime:ValueError: probabilities do not sum to 1

### ISSUE THREAD

**Issue by annrosebright** [LouisFaure/scFates#9]
Hi,

Thanks for generating such a great tool. I am trying to use scFates for our single-cell RNAseq datasets. I am following the "Tree analysis - Bone marrow fates" notebook.  For this analysis, I am using adata I had already processed using scanpy. While performing the pseudo time calculation I get the following error. I am not able to figure out the issue. I checked if its because of the version of NumPy, but I have the exact version needed by scfates. Can it be because I am using an adata already processed by scanpy? I have attached a screenshot of the error plus I have uploaded the HTML file of the whole notebook.  

Please let me know if I can provide any more information.
Thanks in advance. 

![Screenshot 2022-11-24 at 17 36 10](https://user-images.githubusercontent.com/13627744/203840058-c2779203-1c85-4820-a4ea-3bfceffaf626.png)

[S2_trajectory analysis.pdf](https://github.com/LouisFaure/scFates/files/10086541/S2_trajectory.analysis.pdf)

**Comment by LouisFaure** [comment]
It is looking like that some cells do not have their probability assignment to principal node summing to 1. Could check this before running scf.tl.pseudotime:
```python
np.allclose(adata.obsm["X_R"].sum(axis=1),1)
```
if this shows `False`, then it is the case.

Additionally, try running `scf.tl.pseudotime` without multiple mapping (`n_map=1`) and see if you have a similar error.
